<!--Base Pixel Start-->
<script>
    var _paq = _paq || [];
    _paq.push(["trackPageView"]);
    _paq.push(["enableLinkTracking"]);
    (function() {
        var u=(("https:" == document.location.protocol) ? "https" : "http") + "://tr.datatrics.com/";
        _paq.push(["setTrackerUrl", u]);
        _paq.push(["setProjectId", "{{project_id}}"]);
        var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0];
        g.defer=true; g.async=true; g.src=u; s.parentNode.insertBefore(g,s);
    })();
</script>
<!--Base Pixel End-->
