<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials
 * @var \Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials $block
 */
?>

<div id="mm-datatrics-result_error-modal" 
     data-mm-datatrics-endpoind-url="<?= $block->escapeUrl($block->getErrorCheckUrl()) ?>">
    <div id="mm-datatrics-result_error">
        <div class="result"></div>
    </div>
</div>
<?= $block->getButtonHtml() ?>
