<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials
 * @var \Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials $block
 */
?>
<div id="mm-datatrics-result_test-modal" 
     data-mm-datatrics-endpoind-url="<?= $block->escapeUrl($block->getSelftestUrl()) ?>">
    <div id="mm-datatrics-result_test">
        <ul class="result"></ul>
    </div>
</div>
