<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

use Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials;

/**
 * @see \Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials
 * @var Credentials $block
 */
?>
<script>
    require([
        'jquery',
        'prototype'
    ], function (jQuery) {
        var resultSpan = jQuery('#result_api');
        jQuery('#connection_test').click(function () {
            new Ajax.Request('<?= $block->escapeUrl($block->getApiCheckUrl()) ?>', {
                loaderArea: false,
                asynchronous: true,
                onCreate: function () {
                    resultSpan.find('.connecting').show();
                    resultSpan.find('.result').hide();
                },
                onSuccess: function (response) {
                    console.log(response);
                    resultSpan.find('.connecting').hide();
                    let resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        let json = response.responseJSON;
                        if (typeof json.msg != 'undefined') {
                            resultText = json.msg;
                        }
                    }
                    resultSpan.find('.result').show();
                    resultSpan.find('.result').html(resultText);
                }
            });
        });
    });
</script>
<?= $block->getButtonHtml() ?>
<div id="result_api">
    <span class="connecting" style="display: none;">Connecting...</span>
    <span class="result"></span>
</div>
