<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @see \Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials
 * @var \Datatrics\Connect\Block\Adminhtml\System\Config\Button\Credentials $block
 */

?>

<div class="mm-result_version-wrapper" data-mm-endpoind-url="<?= $block->escapeUrl($block->getVersionCheckUrl()) ?>">
    <span><?= $block->escapeHtml($block->getVersion()); ?></span>
    <?= $block->getButtonHtml() ?>
    <div id="mm-result_version"></div>
    <div id="mm-result_changelog-modal" data-mm-endpoind-url="<?= $block->escapeUrl($block->getChangeLogUrl()) ?>">
        <div id="mm-result_changelog">
            <ul class="result"></ul>
        </div>
    </div>
</div>
