name: Codesniffer with the Magento Coding standard
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1

            -   name: Run codesniffer
                run: docker run --rm --volume $(pwd)/:/app/data michielgerritsen/magento-coding-standard:latest
