name: Run setup:upgrade and setup:di:compile
on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - PHP_VERSION: php72-fpm
            MAGENTO_VERSION: 2.3.3
          - PHP_VERSION: php73-fpm
            MAGENTO_VERSION: 2.3.7
          - PHP_VERSION: php74-fpm
            MAGENTO_VERSION: 2.4.2
          - PHP_VERSION: php74-fpm
            MAGENTO_VERSION: 2.4.3-with-replacements
          - PHP_VERSION: php81-fpm
            MAGENTO_VERSION: 2.4.4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: PHP_VERSION=${{ matrix.PHP_VERSION }} MAGENTO_VERSION=magento${{ matrix.MAGENTO_VERSION }} docker-compose -f .github/workflows/templates/docker-compose.yml up -d

      - name: Create branch for Composer and remove version from composer.json
        run: git checkout -b continuous-integration-test-branch && sed -i '/version/d' ./composer.json

      - name: Upload the code into the docker container
        run: docker cp $(pwd) magento-project-community-edition:/data/extensions/ && docker exec magento-project-community-edition composer require datatrics/magento2-integration:dev-continuous-integration-test-branch

      - name: Activate the extension and run setup:upgrade and setup:di:compile
        run: docker exec magento-project-community-edition bash -c "php bin/magento module:enable Datatrics_Connect && php bin/magento setup:upgrade && php bin/magento setup:di:compile"
